repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pipenv run pytest -v
        language: system
        types: [python]
