[tool.black]
line-length = 100
exclude = '''
/(
    \.eggs
  | \.git
)/
'''

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
default_section = "THIRDPARTY"
known_first_party = "video_tools"
