[tool.black]
line-length = 80
exclude = '''
/(
    \.eggs
  | \.git
)/
'''

[tool.isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true
default_section = "THIRDPARTY"
no_lines_before = "LOCALFOLDER"
known_first_party = "video_tools"
